### PR TITLE
++ fixes for race conditions in ConcurrentBatchQueue & TcpClientSession

### PR DESCRIPTION
**Pull request by nj4x**
Detected some race conditions when multiple threads use SuperSocket.ClientEngine to send packets at a high rate.

To reproduce
a) First run [subscriber](https://gist.github.com/nj4x/2e3d6b9bc8b178e7d4da)
b) Then run [publisher](https://gist.github.com/nj4x/483e36b6fa0278673b64)

After some period of time connection will be either broken or hanged or number of events published will not match number of events received by subscriber.

Debug shown some problems in ConcurrentBatchQueue & TcpClientSession addressed by this fix.

### CODE REVIEW

**Comment by nj4x** [comment]
Hi @kerryjiang 

Could you please inform if/when you'll be able to check this issue and proposed fixes?

**Comment by kerryjiang** [comment]
OK, I'll try to do it on these days.
Thanks for the contribution!

**Comment by nj4x** [comment]
Hi @kerryjiang,

Your products are very important to community. E.g. SuperSocket.ClientEngine is used by WebSocket4Net, which is used by WampSharp. Due to this particular bug we're not able to use WampSharp as a client to crossbar.io router in a high-loaded multithreaded environments.

Could you please include fixed version of SuperSocket.ClientEngine into the WebSocket4Net as well?

**Comment by kerryjiang** [comment]
Hello, your fix looks complicated.

I have many ideas below:
1) the cause of this bug should be the switching between m_Entity and m_BackEntity is not safe in concurrent sending situation;
2) Your new ArrayElementPresent property of Entity class seems not necessary because null validating and default null value assignment after dequeue;

**Comment by nj4x** [comment]
On Sat, 19 Sep 2015 at 18:54 Kerry Jiang <notifications@github.com> wrote:

> Hello, your fix looks complicated.
>
> I have many ideas below:
> 1) the cause of this bug should be the switching between m_Entity and
> m_BackEntity is not safe in concurrent sending situation;
>

I've tried to address this as well


> 2) Your new ArrayElementPresent property of Entity class seems not
> necessary because null validating and default null value assignment after
> dequeue;
>

Then you need to fix nullValidator in TcpClientSession

Current:  *(t) => t.Array == null*

is not enough, because ArraySegment is a struct and when t.Array != null
(null validator allows it), t.Count is still == 0 (not fully enqueued)
and as a result e.BytesTransferred == 0 and disconnections in
AsyncTcpSession.Sending_Completed

**Comment by kerryjiang** [comment]
Yes, ArraySegment<byte> is a struct type, but ArraySegment<byte>.Array (byte[]) is a reference type, so it can be null.

The NUnit test case below passed:

[Test]
public void ArraySegmentTest()
{
    var segment = new ArraySegment<byte>();
    Assert.IsNull(segment.Array);
    Assert.AreEqual(0, segment.Count);
}

**Comment by nj4x** [comment]
It is not that I wanted to explain...

One of the problems with ArraySegment and your nullValidator is the
following:

a) Thread A enqueues ArraySegment, it starts to copy segment.Array,
segment.Offset, segment.Count fields
b) Thread B dequeues this ArraySeqment, and nullValidator allows it to do
because segment.Array is not null
c) Thread B copies ArraySegment with {Array!=null, Offset==0, Count==0)
d) AsyncTcpSession.Sending_Completed reports zero bytes transferred (set
breakpoint at line 203) and breaks the connection

Please use the following code to reproduce the issue.
a) First run subscriber <https://gist.github.com/nj4x/2e3d6b9bc8b178e7d4da>
b) Then run publisher <https://gist.github.com/nj4x/483e36b6fa0278673b64>

P.S.
I've spent a lot of time investigating the problems with
SuperSocket.ClientEngine, so you can take the fixes or provide yours - no
matter, the main idea is to make it work for all.

**Comment by kerryjiang** [comment]
Do you mean there is a case that, the dequeue happen when the thread is copying the segment, the segment.Array has been copied but the segment.Count is not copied yet?

Do you mean this situation?

I know you took much time to fix it, but I am looking for a better way to fix it. As the code's original design idea, this issue wouldn't happen. If there is a bug here, I should fix the existing code instead of adding more lines of code to avoid it.

**Comment by nj4x** [comment]
Yes, I meant that.
Code to reproduce a bug is also supplied.

**Comment by kerryjiang** [comment]
Hello, could you try the latest commit?
This fix should have fixed the situation you mentioned.

**Comment by nj4x** [comment]
Thanks!
Please take into account Core/TcpClientSession.cs changes I've done (lines
290-298, 309-315) - those changes have comments explaining another bug.
Meanwhile I'll run my test again on the newly committed
SuperSocket.ClientEngine...

**Comment by kerryjiang** [comment]
OK, finished the code merging.

**Comment by nj4x** [comment]
Same test result - after processing ~5M events AsyncTcpSession hanged.

please consider applying already mentioned Core/TcpClientSession.cs changes.

**Comment by kerryjiang** [comment]
I had made the change:
https://github.com/kerryjiang/SuperSocket.ClientEngine/commit/20a9f273993bcb7d0d66e015453986a0caefbf92

**Comment by nj4x** [comment]
Kerry,

Thanks very much, test of publishing 100M events at 140K events per second
rate shown stable results.

Will you apply fixed ClientEngine to WebSocket4Net at nuget?
I'll ask Elad to apply it to WampSharp product as well.

**Comment by kerryjiang** [comment]
I'll do it on these days.
Another guy asked for it too.

**Comment by kerryjiang** [comment]
Made a nuget release, please have a try:
https://www.nuget.org/packages/WebSocket4Net/

**Pull request closed without merging**
